name: cd
on:
  push:
    branches: [main]

    jobs:
      Deploy:
      - name: Deploy 
        runs-on: ubuntu-latest
        
        steps:
          - name: checkout
            uses: actions/checkout@v4
          - name: get go
            uses: actions/setup-go@v5
            with:
                go-version: 1.23.0
          - name: build app
            run: ./scripts/buildprod.sh

